### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by AspectOfJerry** [AspectOfJerry/BapUtils#15]
**Describe the bug**
Game crashes not on development environement

**Version(s)**
 - v.0.1.2-beta

**To Reproduce**
1. Launch the game
3. Crashes

**Expected behavior**
no crash

**Crash report**
[crash-2023-07-30_06.37.46-client.txt](https://github.com/AspectOfJerry/BapUtils/files/12208175/crash-2023-07-30_06.37.46-client.txt)

**Comment by AspectOfJerry** [comment]
:(

**Comment by AspectOfJerry** [comment]
```
[...]
Caused by: java.lang.ClassNotFoundException: net.jerrydev.baputils.gui.BapGui
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
Caused by: java.lang.NoClassDefFoundError: net/jerrydev/elementa/WindowScreen
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 40 more
Caused by: java.lang.ClassNotFoundException: net.jerrydev.elementa.WindowScreen
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more
```

issue with relocation?

**Comment by Tomassy69** [comment]
ok jerry for the gui, use the forge gui

**Comment by Tomassy69** [comment]
since the mod isnt that big its not a big deal

**Comment by AspectOfJerry** [comment]
For now we can but I still want to use elementa because we are very close to having a working gui it’s just a weird issue with the imports I think. I already made the gui I’ll add screenshots

**Comment by Tomassy69** [comment]
:D

**Comment by AspectOfJerry** [comment]
Yeah I forgot you never saw the gui

**Comment by AspectOfJerry** [comment]
I’ll add a few screenshots later

**Comment by Tomassy69** [comment]
alr

**Comment by AspectOfJerry** [comment]
animation when hovering over the list btw
![2023-08-07_13 47 46](https://github.com/AspectOfJerry/BapUtils/assets/69355304/eabc9296-e6a7-4e73-9df3-78c956a5102b)
![2023-08-07_13 47 56](https://github.com/AspectOfJerry/BapUtils/assets/69355304/7f5d19ea-e41f-4cd1-b0fe-8b9b0e146140)
![2023-08-07_13 48 00](https://github.com/AspectOfJerry/BapUtils/assets/69355304/d159650a-34ee-4581-a524-6215b8fc43df)
quite empty but that's how it looks like

**Comment by AspectOfJerry** [comment]
summary:
```
[14:38:14] [main/ERROR] (FML) Unable to read a class file correctly
 java.lang.IllegalArgumentException: null
[...]
[14:38:14] [main/ERROR] (FML) There was a problem reading the entry META-INF/versions/9/module-info.class in the jar C:\Users\Jerry\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk8\1.8.22\b25c86d47d6b962b9cf0f8c3f320c8a10eea3dd1\kotlin-stdlib-jdk8-1.8.22.jar - probably a corrupt zip
 net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException
[...]
[14:38:14] [main/WARN] (FML) Zip file kotlin-stdlib-jdk8-1.8.22.jar failed to read properly, it will be ignored
 net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException
[...]
[14:38:15] [main/ERROR] (FML) Unable to read a class file correctly
 java.lang.IllegalArgumentException: null
[...]
[14:38:15] [main/ERROR] (FML) There was a problem reading the entry META-INF/versions/9/module-info.class in the jar C:\Users\Jerry\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk7\1.8.22\4dabb8248310d833bb6a8b516024a91fd3d275c\kotlin-stdlib-jdk7-1.8.22.jar - probably a corrupt zip
 net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException
[...]
[14:38:15] [main/WARN] (FML) Zip file kotlin-stdlib-jdk7-1.8.22.jar failed to read properly, it will be ignored
 net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException
[...]
[14:38:15] [main/ERROR] (FML) Unable to read a class file correctly
 java.lang.IllegalArgumentException: null
[...]
[14:38:15] [main/ERROR] (FML) There was a problem reading the entry META-INF/versions/9/module-info.class in the jar C:\Users\Jerry\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.8.22\636bf8b320e7627482771bbac9ed7246773c02bd\kotlin-stdlib-1.8.22.jar - probably a corrupt zip
 net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException
[...]
[14:38:15] [main/WARN] (FML) Zip file kotlin-stdlib-1.8.22.jar failed to read properly, it will be ignored
 net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException
[...]
[14:38:15] [main/ERROR] (FML) Unable to read a class file correctly
 java.lang.IllegalArgumentException: null
[...]
[14:38:15] [main/ERROR] (FML) There was a problem reading the entry META-INF/versions/9/kotlin/reflect/jvm/internal/impl/serialization/deserialization/builtins/BuiltInsResourceLoader.class in the jar C:\Users\Jerry\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-reflect\1.5.10\d6c70f3c0df2457ea0095c61c1fc1188017dc3bc\kotlin-reflect-1.5.10.jar - probably a corrupt zip
 net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException
[...]
[14:38:15] [main/WARN] (FML) Zip file kotlin-reflect-1.5.10.jar failed to read properly, it will be ignored
 net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException
```
